### PR TITLE
Update faq.adoc

### PR DESCRIPTION
**Pull request by amystrayer**
In Line 39, 'Relayers' is capitalized, but most of the rest mentioned are not. Should all instances of this word be capitalized? Either way, consistency is what's important.

### CODE REVIEW

**Comment by frangio** [comment]
Thank you @amystrayer! I agree that it should be non capitalized for consistency.

This PR seems to be based on an older version of the document. Can you check please?

**Comment by amystrayer** [comment]
Hi @frangio ! Yes, sure I can check it. Could you send me the
updated link? I have no idea how to find it!

**Comment by frangio** [comment]
Should be here: https://github.com/OpenZeppelin/docs.openzeppelin.com/blob/master/modules/ROOT/pages/gsn/faq.adoc

**Comment by amystrayer** [comment]
> Should be here: https://github.com/OpenZeppelin/docs.openzeppelin.com/blob/master/modules/ROOT/pages/gsn/faq.adoc

I should have asked before, but is this a different document? Does it need to be fully revised? Because I only checked for the capitalization of 'relayers'.

**Comment by frangio** [comment]
That's fine. :relaxed: 

Closing in favor of #17.

**Pull request closed without merging**
