### PR TITLE
Add stylus docs

### PR DESCRIPTION
**Pull request by ggonzalez94**
We want to publish the docs for stylus before the audit is done. They will be published as  `0.1.0-rc`. I also added the svg and changes so it can be shown in the sidebar(not sure if I missed something here)

DO NOT MERGE BEFORE THIS [PR](https://github.com/OpenZeppelin/rust-contracts-stylus/pull/267)

### CODE REVIEW

**Comment by bidzyyys** [comment]
Blocking PR -> https://github.com/OpenZeppelin/rust-contracts-stylus/pull/267 has been merged.

**Review by bidzyyys — DISMISSED** [review]
Looks good 👍 🚀

**Comment by ggonzalez94** [comment]
I realized I need to adjust the svg image and make the docs appear as part of the tiles on the homepage. Will work on that tomorrow.

**Review by ericglau — DISMISSED** [review]
LGTM, thanks

**Comment by ericglau** [comment]
The URL in the preview https://deploy-preview-415--openzeppelin-docs.netlify.app/contracts-stylus/0.1.0/ shows version `0.1.0` instead of `0.1.0-rc`

**Review by bidzyyys — APPROVED** [review]
Looks good!

**Comment by ggonzalez94** [comment]
> The URL in the preview https://deploy-preview-415--openzeppelin-docs.netlify.app/contracts-stylus/0.1.0/ shows version 0.1.0 instead of 0.1.0-rc

Yeah, I think this is because how our `antora.yml` is defined, but not a big deal since we have a big disclaimer that this is still unaudited and not ready for production. Thanks for catching it though

**Pull request merged**
