### PR TITLE
Add link to starter kit live demo

### PR DESCRIPTION
**Pull request by spalladino**
Related to https://github.com/OpenZeppelin/starter-kit/pull/128

### CODE REVIEW

**Comment by nventuro** [comment]
Is the site already up? Nothing loads on my machine, and I get the following error on the console:

>A web3 provider is not attached to a window. providers.js:25:10

**Comment by nventuro** [comment]
This PR should be updated by rebasing commit https://github.com/OpenZeppelin/docs.openzeppelin.com/pull/93/commits/89cc6d568c62963fc3261a331c3612237bd65afe on top of `master`

**Comment by spalladino** [comment]
@nventuro done!

**Comment by spalladino** [comment]
(also changed base to master!)

**Pull request closed without merging**
