### PR TITLE
Cairo: use release branches instead of tags

### PR DESCRIPTION
**Pull request by ericnordelo**
This should work out of the box since each release has a release branch.

### CODE REVIEW

**Review by ggonzalez94 — COMMENTED** [review]
@ericnordelo this looks good.

- I think we are missing one release branch that is in the docs site(0.15.0-rc.0). I don't think this is a big issue, so I think we are ok removing this
- There are a few release branches that we don't have published in the docs and would appear now(0.2.0, 0.2.1, 0.7.0-rc.0). Here I suggest we solve this [issue](https://github.com/OpenZeppelin/cairo-contracts/issues/1187) first.

Also would be great if we can get a preview before pushing this changes. I think @ericglau has to trigger the workflow?

**Comment by ericnordelo** [comment]
I removed the release candidates, beta releases, and release branches previous to v0.7.0 (cairo 0) from the cairo-contracts repository. Waiting for the deploy-preview as pointed by @ggonzalez94

**Review by ericglau — DISMISSED** [review]
Preview is deployed

**Comment by ericnordelo** [comment]
Updated to doc branches instead, since we already use release branches for bumping the version on releases, and sometimes the docsite may be updated before the release is finished. cc @ggonzalez94

We have to add a doc branch to each corresponding version before merging this.

**Comment by ericnordelo** [comment]
Added a doc branch for every release after 0.10.0 and merged ERC20Permit doc into docs-v0.18.0. Is there a way to re-launch the deploy preview @ericglau? @ggonzalez94 waiting for your confirmation to merge in case you prefer a different approach.

**Comment by ericglau** [comment]
Redeploy failed with error:
```
9:18:02 AM: [13:18:02.273] FATAL (antora): Duplicate nav in 0.12.0@contracts-cairo: modules/ROOT/nav.adoc
9:18:02 AM:   1: docs/modules/ROOT/nav.adoc in https://github.com/OpenZeppelin/cairo-contracts (ref: docs-v0.12.0)
9:18:02 AM:   2: docs/modules/ROOT/nav.adoc in https://github.com/OpenZeppelin/cairo-contracts (ref: docs-v0.13.0)
```

**Comment by ericnordelo** [comment]
Whoops. Version conflicts fixed @ericglau.

**Comment by ericglau** [comment]
Redeployment succeeded at https://deploy-preview-419--openzeppelin-docs.netlify.app/
Build log [here](https://app.netlify.com/sites/openzeppelin-docs/deploys/671906467011ef0b2e01a1bc). It didn't refresh the github checks, but it looks fine to me.

**Comment by ericnordelo** [comment]
@ggonzalez94 a kindly reminder that the sooner we merge this the sooner we get ERC20Permit entries in the docsite.

**Review by ggonzalez94 — DISMISSED** [review]
@ericnordelo looks good sorry for the delay. Can you please update our release process to include the step of creating the docs branch from the release branch?
Thanks!

**Comment by ggonzalez94** [comment]
@ericglau I think we need one final deploy preview before merging this, could you please approve it? 🙏 
I'm still waiting for access to Netlify

**Comment by ericnordelo** [comment]
> Can you please update our release process to include the step of creating the docs branch from the release branch?

https://github.com/OpenZeppelin/cairo-contracts/pull/1195

Done!

**Review by immrsd — DISMISSED** [review]

**Comment by ericglau** [comment]
I've redeployed the preview.
[Build result](https://app.netlify.com/sites/openzeppelin-docs/deploys/67322f2b6193b14a199adff9)
[Preview link](https://deploy-preview-419--openzeppelin-docs.netlify.app/)

**Review by ericglau — APPROVED** [review]

**Pull request merged**
