### PR TITLE
Update polkadot runtime templates reference

### PR DESCRIPTION
**Pull request by ggonzalez94**
We are about to release v2 of the templates. This PR updates the branch to our release branch and also uses the new repo url(the name was changed, and while redirect works for consistency is better to update it).

**We can merge this PR, but release should happen after the release on the polkadot runtime repo is done.**

### CODE REVIEW

**Review by ozgunozerk — DISMISSED** [review]

**Comment by ericglau** [comment]
I'm not sure why the [deploy preview](https://deploy-preview-412--openzeppelin-docs.netlify.app/substrate-runtimes/0.1.0/) shows version `0.1.0` in the URL, but the rest LGTM.

**Comment by ggonzalez94** [comment]
Made some changes so that the docs reflect the different versions after reading [this](https://docs.antora.org/antora/latest/playbook/content-branches/) and seeing other examples, that also fixed the url. The actual version should be `2.0.0 `instead of `1.1.0`, so I already fixed that in the polkadot-runtimes repo.
This is now ready for final review and merge. @ericglau remind me, does this get published automatically after merging or do we need to trigger it manually? I still need to add the webhook you shared with me for continuous updates going forward.

**Review by ericglau — APPROVED** [review]
LGTM

**Comment by ericglau** [comment]
@ggonzalez94 I reran the Netlfiy deploy preview and it properly shows `2.0.0` now.

>  does this get published automatically after merging or do we need to trigger it manually?

This repo's PRs get published automatically after merging.  But changes in another repo e.g. https://github.com/OpenZeppelin/polkadot-runtime-templates need to trigger the webhook in order for the docs site to rebuild.

**Pull request merged**
